-- Create storage buckets for course assets
-- Run this in the Supabase SQL Editor or via CLI

-- 1. Course audio bucket (ElevenLabs TTS output)
INSERT INTO storage.buckets (id, name, public)
VALUES ('course-audio', 'course-audio', true)
ON CONFLICT (id) DO NOTHING;

-- 2. Course assets bucket (ComfyUI/ThinkDiffusion images, territory landscapes, silhouettes)
INSERT INTO storage.buckets (id, name, public)
VALUES ('course-assets', 'course-assets', true)
ON CONFLICT (id) DO NOTHING;

-- 3. Course videos bucket (HeyGen avatar videos, private with signed URLs)
INSERT INTO storage.buckets (id, name, public)
VALUES ('course-videos', 'course-videos', false)
ON CONFLICT (id) DO NOTHING;

-- Storage policies for course-audio (public read, admin upload)
CREATE POLICY "Public read course-audio"
ON storage.objects FOR SELECT
USING (bucket_id = 'course-audio');

CREATE POLICY "Admin upload course-audio"
ON storage.objects FOR INSERT
WITH CHECK (
  bucket_id = 'course-audio'
  AND (
    auth.role() = 'service_role'
    OR EXISTS (
      SELECT 1 FROM public.profiles
      WHERE id = auth.uid() AND is_admin = true
    )
  )
);

CREATE POLICY "Admin update course-audio"
ON storage.objects FOR UPDATE
USING (
  bucket_id = 'course-audio'
  AND (
    auth.role() = 'service_role'
    OR EXISTS (
      SELECT 1 FROM public.profiles
      WHERE id = auth.uid() AND is_admin = true
    )
  )
);

CREATE POLICY "Admin delete course-audio"
ON storage.objects FOR DELETE
USING (
  bucket_id = 'course-audio'
  AND (
    auth.role() = 'service_role'
    OR EXISTS (
      SELECT 1 FROM public.profiles
      WHERE id = auth.uid() AND is_admin = true
    )
  )
);

-- Storage policies for course-assets (public read, admin upload)
CREATE POLICY "Public read course-assets"
ON storage.objects FOR SELECT
USING (bucket_id = 'course-assets');

CREATE POLICY "Admin upload course-assets"
ON storage.objects FOR INSERT
WITH CHECK (
  bucket_id = 'course-assets'
  AND (
    auth.role() = 'service_role'
    OR EXISTS (
      SELECT 1 FROM public.profiles
      WHERE id = auth.uid() AND is_admin = true
    )
  )
);

CREATE POLICY "Admin update course-assets"
ON storage.objects FOR UPDATE
USING (
  bucket_id = 'course-assets'
  AND (
    auth.role() = 'service_role'
    OR EXISTS (
      SELECT 1 FROM public.profiles
      WHERE id = auth.uid() AND is_admin = true
    )
  )
);

CREATE POLICY "Admin delete course-assets"
ON storage.objects FOR DELETE
USING (
  bucket_id = 'course-assets'
  AND (
    auth.role() = 'service_role'
    OR EXISTS (
      SELECT 1 FROM public.profiles
      WHERE id = auth.uid() AND is_admin = true
    )
  )
);

-- Storage policies for course-videos (private, signed URLs only)
-- Only service_role and admins can upload
-- Read access via signed URLs (generated by the lesson API)
CREATE POLICY "Admin upload course-videos"
ON storage.objects FOR INSERT
WITH CHECK (
  bucket_id = 'course-videos'
  AND (
    auth.role() = 'service_role'
    OR EXISTS (
      SELECT 1 FROM public.profiles
      WHERE id = auth.uid() AND is_admin = true
    )
  )
);

CREATE POLICY "Admin update course-videos"
ON storage.objects FOR UPDATE
USING (
  bucket_id = 'course-videos'
  AND (
    auth.role() = 'service_role'
    OR EXISTS (
      SELECT 1 FROM public.profiles
      WHERE id = auth.uid() AND is_admin = true
    )
  )
);

CREATE POLICY "Admin delete course-videos"
ON storage.objects FOR DELETE
USING (
  bucket_id = 'course-videos'
  AND (
    auth.role() = 'service_role'
    OR EXISTS (
      SELECT 1 FROM public.profiles
      WHERE id = auth.uid() AND is_admin = true
    )
  )
);

-- Enrolled users can read course-videos (for signed URL generation)
CREATE POLICY "Enrolled users read course-videos"
ON storage.objects FOR SELECT
USING (
  bucket_id = 'course-videos'
  AND (
    auth.role() = 'service_role'
    OR EXISTS (
      SELECT 1 FROM public.profiles
      WHERE id = auth.uid() AND is_admin = true
    )
    OR EXISTS (
      SELECT 1 FROM public.enrollments
      WHERE user_id = auth.uid()
    )
  )
);
